version: '2'
services:
    librecat:
        build:
            context: .
            dockerfile: Dockerfile_Dev
        image: librecat:latest
        ports:
            - "5001:5001"
        links:
            - "mysql:mysqldb"
            - "elasticsearch:searchnode"
        env_file:
            - ./conf/local.env
        volumes:
            - "~/librecat-logs:/srv/LibreCat/logs"
# If you want to tweak around or have permanent data, according to
# instruction in wiki-page, you should comment in the line below.
            #- "./docker-entrypoint.sh:/srv/LibreCat/docker-entrypoint.sh"
        depends_on:
            - mysql
            - elasticsearch
        restart: always
# if you with to use remote Database or Index, please
# comment out the related section. that includes `links`
# as well as `depends on` above.
    mysql:
        image: mysql:5.5
        ports:
            - "3306:3306"
        env_file:
            - ./conf/mysql.env
        volumes:
            - "~/librecat-mysql:/var/lib/mysql"
        restart: always
    elasticsearch:
        image: elasticsearch:1.7
        ports:
            - "9300:9300"
            - "9200:9200"
        volumes:
            - "~/librecat-index:/usr/share/elasticsearch/data"
        restart: always
